Updated property name and added port prop
countr/docs pull request #2
Opened 2020-11-09 13:22 UTC by 000Lonewolf

- Updated property name of `webhook` to `webhookUrl`
- Added `port` property with description

2020-11-09 18:34 UTC, promise requested changes
I've requested some changes, but everything else looks good.

2020-11-09 18:34 UTC, promise commented on docs/selfhosting.md
> +| `port`         | `1001`       | Creates an express server on `localhost:port` to show information about shards. |
Don't document this, it's only for the live version

2020-11-11 09:25 UTC, 000Lonewolf commented on docs/selfhosting.md
> +| `port`         | `1001`       | Creates an express server on `localhost:port` to show information about shards. |
Done.

2020-11-11 13:39 UTC, promise approved these changes

2020-11-11 13:39 UTC, merged